# Generated by Django 4.1.3 on 2022-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveConcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(max_length=20, verbose_name='Дата заполнение')),
                ('factory_name', models.CharField(max_length=50, verbose_name='Название завода')),
                ('object_name', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('block', models.IntegerField(verbose_name='блок')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка бетона')),
                ('constructive', models.CharField(max_length=50, verbose_name='Конструктив')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('fact_concrete', models.IntegerField(verbose_name='Факт')),
                ('sum_concrete', models.IntegerField(verbose_name='Итого залито')),
                ('accepted', models.CharField(max_length=100, verbose_name='Кто принимал')),
            ],
            options={
                'verbose_name': 'Таблица бетона',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
